version: '3'
services:
  php-fpm:
    build:
      context: ./infrastructure/php
      dockerfile: ./Dockerfile
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-net
  nginx:
    image: nginx:1.15
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-net
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meetmethere
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    networks:
      - app-net

networks:
  app-net:
    driver: bridge


